---
application:
  name: "patricia-music-bot"
  project: "musicbot"
  organization: "QoveryCommunity"
routers:
- name: "main-patricia-music-bot"
  routes:
  - application_name: "patricia-music-bot"
    paths:
    - "/*"
